### ISSUE TITLE
The input struct example

### ISSUE THREAD

**Issue by YANG-DEMIN** [dciliberti/matlab-datcom-interface#1]
Hello, my friend. I am excited for your work, which is meaningful. 
I am doing the similiar work to edit and show DATCOM easily. After repeating your work, I want to add the drawing function and shape optimization function.

When I try to run your code, it need a input struct. ` function filename = writeDatcomInput(s)`
So, can you share your struct example with me?

Thanks very much!

Yours,
YANG

**Comment by YANG-DEMIN** [comment]
Oh, sorry. I think I find the struct……
It laid on another file.

**Comment by YANG-DEMIN** [comment]
Sorry,  I come back. 
I encountered the problem when run the datcom. Your code generated the `.dcm` file correctly, but it failed to generated `.out `file.
As you say, I add the bin to PATH,  it's useless. 

I found that I miss the `datcom.exe` in `bin` directory. It's normal?

![image](https://user-images.githubusercontent.com/53554275/119595529-49181000-be10-11eb-84ee-91fe87ea522b.png)

Looking forward your reply.

Yours,
YANG

**Comment by dciliberti** [comment]
Hello,
if you double-click on any `.dcm` file it should automatically execute Digital Datcom. It is not an issue of my code.

Also, there is no `datcom.exe` in `bin` folder. The `.bat` file calls the executable it needs. 

Please, double check if the `bin` folder has been added to your PATH correctly. Eventually, restart the computer. 

Good luck

**Comment by YANG-DEMIN** [comment]
> Hello,if you double-click on any `.dcm` file it should automatically execute Digital Datcom. It is not an issue of my code. Also, there is no `datcom.exe` in `bin` folder. The `.bat` file calls the executable it needs. Please, double check if the `bin` folder has been added to your PATH correctly. Eventually, restart the computer. Good luck

Thank you very much, my friend. I fixed the problem 2 hours ago. 
The reason is that the default application of opening dcm file is Notepad. After switching it to datcom, it worked well.

I will did the following work to optimize my aircraft.

By the way, your code only have the `wing` part,  I will add `Body` and` Tail` part laterly. 

When finished it,  I hope I can merge it to your code.
Thanks again!

**Comment by dciliberti** [comment]
Thank you,
I made this little project to generate a few charts to show my students the effects of Mach number and planform parameters on wing and airfoil aerodynamics, things that cannot be easily predicted with the simple methods available on textbooks. Then I've abandoned it, because of many other things to do.

As I see, it is useful anyone who needs it.

Best regards,
Danilo

**Comment by YANG-DEMIN** [comment]
Yes, it's a useful job. Because there are not interfaces for datcom, and DATCOM PRO is too expensive. 

I am using it to finish my master's degree. I hope it will become an easy tools to predict aerodynamics.

After finished it, I will pull it to you.

Best regards,
Yang
